### PR TITLE
[TC-7523] Add shipment webhook

### PR DESCRIPTION
**Pull request by marcmatt**
This PR adds the shipment webhook. This was already partly done before this PR.

### CODE REVIEW

**Review by Sjorstradecloud — APPROVED** [review]
Looks good, no notes

**Review by ghost — APPROVED** [review]
@marcmatt the link didn't work so I couldn't review it in Gitbook, but telling from the code, it looks good.

**Comment by marcmatt** [comment]
@roy-tc I tried, but could not find a way to render the PR in Gitbook

**Comment by ghost** [comment]
@marcmatt yeah me neither :/ this is a quite shitty feature of "Git"books... :(

**Pull request merged**
